"""Tests for package version resolution.

``cloudx_proxy/_version.py`` is generated by setuptools_scm at build time and
is not committed, so ``from ._version import __version__`` raised
ModuleNotFoundError in a plain source checkout - the package could not be
imported at all until it had been built.
"""

import sys

import pytest

import cloudx_proxy
from cloudx_proxy import _resolve_version


class TestResolveVersion:
    def test_version_is_a_non_empty_string(self):
        assert isinstance(cloudx_proxy.__version__, str)
        assert cloudx_proxy.__version__

    def test_falls_back_to_distribution_metadata(self, monkeypatch):
        """A source checkout has no _version.py; installed metadata still does."""
        monkeypatch.setitem(sys.modules, "cloudx_proxy._version", None)

        resolved = _resolve_version()

        assert isinstance(resolved, str)
        assert resolved
        assert resolved != "0.0.0+unknown"

    def test_sentinel_when_nothing_knows_the_version(self, monkeypatch):
        """Neither built nor installed: import must still succeed."""
        import importlib.metadata

        monkeypatch.setitem(sys.modules, "cloudx_proxy._version", None)

        def not_found(name):
            raise importlib.metadata.PackageNotFoundError(name)

        monkeypatch.setattr(importlib.metadata, "version", not_found)

        assert _resolve_version() == "0.0.0+unknown"

    def test_prefers_the_build_time_version(self, monkeypatch):
        import importlib.metadata

        def unexpected(name):
            raise AssertionError("metadata should not be consulted when _version exists")

        monkeypatch.setattr(importlib.metadata, "version", unexpected)

        # _version.py is present in this tree (uv sync built it), so this must
        # not reach the metadata fallback at all.
        pytest.importorskip("cloudx_proxy._version")
        assert _resolve_version()


class TestVersionInGeneratedConfig:
    def test_config_header_carries_the_version(self, tmp_path):
        from cloudx_proxy.setup import CloudXSetup

        setup = CloudXSetup(
            ssh_dir=str(tmp_path / "ssh"),
            ssh_host_prefix="cloudx",
            non_interactive=True,
        )
        setup.setup_ssh_config("dev", "i-0123456789abcdef0", "web1")

        header = setup.ssh_config_file.read_text().splitlines()[0]
        assert header == (
            f"# SSH Configuration - Managed by cloudx-proxy v{cloudx_proxy.__version__}"
        )
        assert "unknown" not in header
